version: "3.9"

name: taskservice

services:
  api:
    build:
      context: .
      dockerfile: src/TaskService.Api/Dockerfile
    image: taskservice-api:local
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_ENVIRONMENT=Development
      - MongoDB__ConnectionString=mongodb://mongo:27017
      - Redis__ConnectionString=redis:6379
    ports:
      - "5214:8080" # host:container
    networks:
      - appnet

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - appnet

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "20", "1", "--loglevel", "warning"]
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - appnet

volumes:
  mongo_data:
  redis_data:

networks:
  appnet:
    driver: bridge
